version: '3.8'

services:
  web-server:
    image: nginx:alpine
    container_name: web-server
    ports:
      - "80:80"
    networks:
      nmap-network:
        ipv4_address: 172.28.0.2

  ftp-server:
    image: delfer/alpine-ftp-server
    container_name: ftp-server
    environment:
      - USERS=user:password:1000:1000
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      nmap-network:
        ipv4_address: 172.28.0.3

  ssh-server:
    image: linuxserver/openssh-server
    container_name: ssh-server
    platform: linux/arm64/v8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=user
    ports:
      - "2222:2222"
    networks:
      nmap-network:
        ipv4_address: 172.28.0.4

  mysql-server:
    image: mariadb:latest
    container_name: db-server
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
    networks:
      nmap-network:
        ipv4_address: 172.28.0.5

networks:
  nmap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16